from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MemoryScrollsAssets: 


	# Click Rule Assets
	# 进入卷一 
	C_MS_SCROLL_1 = RuleClick(roi_front=(170,157,279,192), roi_back=(170,157,279,192), name="ms_scroll_1")
	# 进入卷二 
	C_MS_SCROLL_2 = RuleClick(roi_front=(490,135,297,210), roi_back=(490,135,297,210), name="ms_scroll_2")
	# 进入卷三 
	C_MS_SCROLL_3 = RuleClick(roi_front=(836,135,304,210), roi_back=(836,135,304,210), name="ms_scroll_3")
	# 进入卷四 
	C_MS_SCROLL_4 = RuleClick(roi_front=(137,389,305,206), roi_back=(137,389,305,206), name="ms_scroll_4")
	# 进入卷五 
	C_MS_SCROLL_5 = RuleClick(roi_front=(491,390,303,207), roi_back=(491,390,303,207), name="ms_scroll_5")
	# 进入卷六 
	C_MS_SCROLL_6 = RuleClick(roi_front=(835,389,303,204), roi_back=(835,389,303,204), name="ms_scroll_6")
	# 贡献完成跳结算 
	C_MS_CONTRIBUTED = RuleClick(roi_front=(108,509,993,190), roi_back=(108,509,993,190), name="ms_contributed")


	# Image Rule Assets
	# 进入绘卷主界面 
	I_MS_ENTER = RuleImage(roi_front=(1169,155,24,55), roi_back=(1169,155,24,55), threshold=0.5, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_enter.png", path="./ms/ms_ms_enter.png")
	# 判断是否处于绘卷主界面 
	I_MS_MAIN = RuleImage(roi_front=(689,3,40,50), roi_back=(689,3,40,50), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_main.png", path="./ms/ms_ms_main.png")
	# 退出到召唤界面 
	I_MS_BACK = RuleImage(roi_front=(32,31,43,45), roi_back=(32,31,43,45), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_back.png", path="./ms/ms_ms_back.png")
	# 关闭分卷捐献界面 
	I_MS_CLOSE = RuleImage(roi_front=(1145,48,39,41), roi_back=(1145,48,39,41), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_close.png", path="./ms/ms_ms_close.png")
	# 贡献碎片 
	I_MS_CONTRIBUTE = RuleImage(roi_front=(1013,583,125,35), roi_back=(1013,583,125,35), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_contribute.png", path="./ms/ms_ms_contribute.png")
	# 贡献碎片完成 
	I_MS_CONTRIBUTED = RuleImage(roi_front=(493,232,63,40), roi_back=(493,232,63,40), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_contributed.png", path="./ms/ms_ms_contributed.png")
	# 绘卷100% 
	I_MS_COMPLETE = RuleImage(roi_front=(397,593,100,21), roi_back=(397,593,100,21), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_complete.png", path="./ms/ms_ms_complete.png")
	# 小绘卷不足 
	I_MS_ZERO_S = RuleImage(roi_front=(968,160,51,27), roi_back=(968,160,51,27), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_zero_s.png", path="./ms/ms_ms_zero_s.png")
	# 中绘卷不足 
	I_MS_ZERO_M = RuleImage(roi_front=(967,312,54,26), roi_back=(967,312,54,26), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_zero_m.png", path="./ms/ms_ms_zero_m.png")
	# 大绘卷不足 
	I_MS_ZERO_L = RuleImage(roi_front=(968,464,51,27), roi_back=(968,464,51,27), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_zero_l.png", path="./ms/ms_ms_zero_l.png")
	# 小绘卷加号 
	I_MS_ADD_S = RuleImage(roi_front=(1090,121,39,35), roi_back=(1090,121,39,35), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_add_s.png", path="./ms/ms_ms_add_s.png")
	# 中绘卷加号 
	I_MS_ADD_M = RuleImage(roi_front=(1090,272,39,35), roi_back=(1090,272,39,35), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_add_m.png", path="./ms/ms_ms_add_m.png")
	# 大绘卷加号 
	I_MS_ADD_L = RuleImage(roi_front=(1089,424,39,35), roi_back=(1089,424,39,35), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_add_l.png", path="./ms/ms_ms_add_l.png")
	# 绘卷到达95%进度 
	I_MS_COMPLETE_95 = RuleImage(roi_front=(655,594,4,18), roi_back=(655,594,4,18), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_complete_100.png", path="./ms/ms_ms_complete_100.png")
	# 小碎片 
	I_MS_FRAGMENT_S = RuleImage(roi_front=(290,677,40,35), roi_back=(290,677,40,35), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_fragment_s.png", path="./ms/ms_ms_fragment_s.png")
	# 小碎片满50 
	I_MS_FRAGMENT_S_50 = RuleImage(roi_front=(473,517,60,25), roi_back=(473,517,60,25), threshold=0.7, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_fragment_s_50.png", path="./ms/ms_ms_fragment_s_50.png")
	# description 
	I_MS_FRAGMENT_S_VERIFICATION = RuleImage(roi_front=(522,318,100,100), roi_back=(522,318,100,100), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_fragment_s_verification.png", path="./ms/ms_ms_fragment_s_verification.png")
	# 打开排行榜 
	I_MS_OPEN_LEAGUETABLES = RuleImage(roi_front=(1187,290,45,117), roi_back=(1187,290,45,117), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_open_leaguetables.png", path="./ms/ms_ms_open_leaguetables.png")
	# 打开回忆（准备捐赠） 
	I_MS_OPEN_MEMORY = RuleImage(roi_front=(1185,148,45,117), roi_back=(1185,148,45,117), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_open_memory.png", path="./ms/ms_ms_open_memory.png")
	# 我的排名 
	I_MS_MY_RANKING = RuleImage(roi_front=(836,531,107,21), roi_back=(836,531,107,21), threshold=0.8, method="Template matching", file="./tasks/MemoryScrolls/ms/ms_ms_my_ranking.png", path="./ms/ms_ms_my_ranking.png")


	# Ocr Rule Assets
	# 累计绘卷分数 
	O_MS_ACCRUED_SCORES = RuleOcr(roi=(916,600,62,35), area=(916,600,62,35), mode="Digit", method="Default", keyword="", name="ms_accrued_scores")
	# 本次捐献绘卷分数 
	O_MS_THIS_SCORES = RuleOcr(roi=(915,562,62,35), area=(915,562,62,35), mode="Digit", method="Default", keyword="", name="ms_this_scores")
	# 绘卷进度 
	O_MS_PROGRESS = RuleOcr(roi=(403,593,35,28), area=(403,593,35,28), mode="Digit", method="Default", keyword="", name="ms_progress")
	# 小碎片掉落数量 
	O_MS_COUNT_S = RuleOcr(roi=(473,517,60,25), area=(473,517,60,25), mode="DigitCounter", method="Default", keyword="", name="ms_count_s")
	# 绘卷排名 
	O_MS_MY_RANKING = RuleOcr(roi=(829,586,51,38), area=(829,586,51,38), mode="Digit", method="Default", keyword="", name="ms_my_ranking")


	# Swipe Rule Assets
	# 小碎片拉满 
	S_MS_SWIPE_S = RuleSwipe(roi_front=(838,199,37,27), roi_back=(1177,172,74,77), mode="default", name="ms_swipe_s")
	# 中碎片拉满 
	S_MS_SWIPE_M = RuleSwipe(roi_front=(838,352,37,23), roi_back=(1175,328,72,75), mode="default", name="ms_swipe_m")
	# 大碎片拉满 
	S_MS_SWIPE_L = RuleSwipe(roi_front=(839,503,34,25), roi_back=(1175,481,77,73), mode="default", name="ms_swipe_l")


