from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class DailyTriflesAssets: 


	# Image Rule Assets
	# 进入普通召唤 
	I_BM_ENTER = RuleImage(roi_front=(435,601,62,68), roi_back=(435,601,62,68), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/broken_amulet/broken_amulet_bm_enter.png")
	# 确定 
	I_BM_CONFIRM = RuleImage(roi_front=(418,620,173,59), roi_back=(418,620,173,59), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/broken_amulet/broken_amulet_bm_confirm.png")
	# 再次召唤 
	I_BM_AGAIN = RuleImage(roi_front=(686,617,178,60), roi_back=(686,617,178,60), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/broken_amulet/broken_amulet_bm_again.png")


	# Ocr Rule Assets
	# 左上角的数量 
	O_BA_AMOUNT_1 = RuleOcr(roi=(568,15,79,29), area=(568,15,79,29), mode="Digit", method="Default", keyword="", name="ba_amount_1")
	# 召唤的时候的数量 
	O_BA_AMOUNT_2 = RuleOcr(roi=(762,570,118,35), area=(762,570,118,35), mode="DigitCounter", method="Default", keyword="", name="ba_amount_2")


	# Image Rule Assets
	# guild_info 
	I_GUILD_INFO = RuleImage(roi_front=(1181,625,50,45), roi_back=(1181,625,50,45), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/guild_info.png")
	# guild_management 
	I_GUILD_MANAGEMENT = RuleImage(roi_front=(260,84,66,45), roi_back=(260,84,66,45), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/guild_management.png")
	# guild_management_1 
	I_GUILD_MANAGEMENT_1 = RuleImage(roi_front=(352,612,75,37), roi_back=(352,612,75,37), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/guild_management_1.png")
	# recruit_members 
	I_RECRUIT_MEMBERS = RuleImage(roi_front=(339,372,120,30), roi_back=(291,346,213,233), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/recruit_members.png")
	# member_add 
	I_MEMBER_ADD = RuleImage(roi_front=(1100,155,39,38), roi_back=(1075,137,86,400), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/member_add.png")
	# member_flush 
	I_MEMBER_FLUSH = RuleImage(roi_front=(1004,615,92,32), roi_back=(1004,615,92,32), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/member_flush.png")
	# 发布招新公告 
	I_POSTS = RuleImage(roi_front=(244,526,71,37), roi_back=(244,526,71,37), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/guild/posts.png")


	# Image Rule Assets
	# description 
	I_L_FRIENDS = RuleImage(roi_front=(67,625,70,72), roi_back=(67,625,70,72), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/love/love_l_friends.png")
	# l_friends_select 
	I_L_FRIENDS_SELECT = RuleImage(roi_front=(165,100,52,30), roi_back=(141,86,103,56), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/l_friends_select.png")
	# description 
	I_L_LOVE = RuleImage(roi_front=(123,625,67,72), roi_back=(123,625,67,72), threshold=0.9, method="Template matching", file="./tasks/DailyTrifles/love/love_l_love.png")
	# 一键收取 
	I_L_COLLECT = RuleImage(roi_front=(47,537,129,56), roi_back=(47,537,129,56), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/love_l_collect.png")
	# 吉闻 
	I_LUCK_MSG = RuleImage(roi_front=(22,47,46,27), roi_back=(22,47,46,27), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_luck_msg.png")
	# 一键祝福 
	I_ONE_CLICK_BLESS = RuleImage(roi_front=(1115,500,93,33), roi_back=(1115,500,93,33), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_one_click_bless.png")
	# 点击祝福 
	I_CLICK_BLESS = RuleImage(roi_front=(617,442,92,39), roi_back=(617,442,92,39), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_click_bless.png")
	# 吉闻页 
	I_LUCK_TITLE = RuleImage(roi_front=(600,52,131,67), roi_back=(600,52,131,67), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/Screenshots_luck_title.png")
	# 好友羁绊提升弹窗 
	I_FRIENDSHIP_UP = RuleImage(roi_front=(1147,80,27,28), roi_back=(1147,80,27,28), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/love/friendship_up.png")


	# Image Rule Assets
	# 集结 
	I_MASSED = RuleImage(roi_front=(213,521,50,56), roi_back=(213,521,50,56), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/massed/massed.png")
	# battle 
	I_BATTLE = RuleImage(roi_front=(1068,605,117,35), roi_back=(1068,605,117,35), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/massed/battle.png")
	# after_on 
	I_AFTER_ON = RuleImage(roi_front=(1008,432,99,30), roi_back=(1008,432,99,30), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/massed/after_on.png")
	# click_any_position 
	I_CLICK_ANY_POSITION = RuleImage(roi_front=(542,511,214,28), roi_back=(542,511,214,28), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/massed/click_any_position.png")


	# Image Rule Assets
	# 礼包屋 
	I_ROOM_GIFT = RuleImage(roi_front=(1138,658,52,40), roi_back=(1119,621,103,94), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_room_gift.png")
	# description 
	I_GIFT_RECOMMEND = RuleImage(roi_front=(1183,454,53,64), roi_back=(1161,74,105,484), threshold=0.7, method="Template matching", file="./tasks/DailyTrifles/store/store_gift_recommend.png")
	# 免费一抽领黑蛋 
	I_GIFT_SIGN = RuleImage(roi_front=(629,192,129,149), roi_back=(130,129,891,473), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_gift_sign.png")
	# 体力 
	I_SPECIAL_SUSHI = RuleImage(roi_front=(180,130,800,460), roi_back=(180,130,800,460), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_sushi.png")
	# 购买时货币类型为勾玉 
	I_STORE_COST_TYPE_JADE = RuleImage(roi_front=(600,490,50,60), roi_back=(600,490,50,60), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/store/store_cost_type_jade.png")


	# Ocr Rule Assets
	# 商店Special购买体力所需勾玉数量，roiBack为动态调整，故此设置为0，0，0，0 
	O_STORE_SUSHI_PRICE = RuleOcr(roi=(0,0,0,0), area=(0,0,0,0), mode="Digit", method="Default", keyword="", name="store_sushi_price")
	# 商店每日免费签到 
	O_STORE_FREE_SIGN = RuleOcr(roi=(136,173,414,204), area=(136,173,414,204), mode="Full", method="Default", keyword="免费", name="store_free_sign")
	# 商店签到页面（日常） 
	O_STORE_DAILY = RuleOcr(roi=(1183,73,51,484), area=(1183,73,51,484), mode="Full", method="Default", keyword="日常", name="store_daily")


	# Image Rule Assets
	# 点击今忆召唤票 
	I_RECALL_TICKET = RuleImage(roi_front=(595,586,65,76), roi_back=(595,586,65,76), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_ticket.png")
	# 今忆召唤单抽 
	I_RECALL_ONE_TICKET = RuleImage(roi_front=(459,604,76,76), roi_back=(459,604,76,76), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_one_ticket.png")
	# description 
	I_RECALL_SM_CONFIRM = RuleImage(roi_front=(424,628,174,61), roi_back=(424,628,174,61), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/recall_sm_confirm.png")
	# 抽到的时候出现的 
	I_SM_CONFIRM_2 = RuleImage(roi_front=(377,630,206,62), roi_back=(377,630,206,62), threshold=0.8, method="Template matching", file="./tasks/DailyTrifles/summonRecall/sm_sm_confirm_2.png")


	# Ocr Rule Assets
	# 今忆抽卡区域 
	O_RECALL_TICKET_AREA = RuleOcr(roi=(590,660,100,32), area=(590,660,100,32), mode="Single", method="Default", keyword="", name="recall_ticket_area")
	# 选择抽卡区域 
	O_SELECT_SM = RuleOcr(roi=(0,0,100,720), area=(0,0,100,720), mode="Single", method="Default", keyword="", name="select_sm")
	# description 
	O_SELECT_SM1 = RuleOcr(roi=(27,130,45,38), area=(27,130,45,38), mode="Single", method="Default", keyword="", name="select_sm1")
	# description 
	O_SELECT_SM2 = RuleOcr(roi=(26,216,45,38), area=(26,216,45,38), mode="Single", method="Default", keyword="", name="select_sm2")
	# description 
	O_SELECT_SM3 = RuleOcr(roi=(26,304,45,38), area=(26,304,45,38), mode="Single", method="Default", keyword="", name="select_sm3")
	# description 
	O_SELECT_SM4 = RuleOcr(roi=(26,397,45,38), area=(26,397,45,38), mode="Single", method="Default", keyword="", name="select_sm4")


